[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[client]
showSidebarNavigation = true

[runner]
fastReruns = true

[server]
enableXsrfProtection = true
enableCORS = true
maxUploadSize = 50
